name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    environment:
      name: pypi
      url: https://pypi.org/project/unidata-blocks/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
